const actionType = {
  PLAYING: "PLAYING",
  CUR_SONG: "CUR_SONG",
  VOLUME: "VOLUME",
  VOLUME_VALUE: "VOLUME_VALUE",

  SECTION_TYPE_PLAYLIST: "SECTION_TYPE_PLAYLIST",
  SECTION_TYPE_DISPLAY: "SECTION_TYPE_DISPLAY",
  RAIN: "RAIN",

  SCREEN: "SCREEN",
};

export default actionType;
